Add mbaijal to AWS org
kubeflow/internal-acls pull request #407
Opened 2020-11-16 20:08 UTC by RedbackThomson

Adds `mbaijal` to the `AWS` Kubeflow org.

2020-11-16 20:24 UTC, terrytangyuan reviewed
/cc @Jeffwan @PatrickXYS

2020-11-16 20:59 UTC, PatrickXYS commented
/lgtm

2020-11-19 02:41 UTC, PatrickXYS requested changes

2020-11-19 02:41 UTC, PatrickXYS commented on github-orgs/kubeflow/org.yaml
> +            - mbaijal
Can we keep the name alphabetical?

2020-11-19 18:45 UTC, RedbackThomson commented
Alphabetized @PatrickXYS

2020-11-19 18:48 UTC, Jeffwan approved these changes

2020-11-19 18:50 UTC, PatrickXYS commented
/cc @Bobgy 

Can you help approve?

2020-11-19 23:54 UTC, Bobgy commented
/lgtm
/approve

2020-11-19 23:54 UTC, merged