add jocstaa to members
kubeflow/internal-acls pull request #574
Opened 2022-10-03 18:43 UTC by JOCSTAA

2022-10-03 21:18 UTC, connor-mccarthy commented
/ok-to-test
/assign @chensun

2022-10-03 21:55 UTC, connor-mccarthy requested changes

2022-10-03 21:55 UTC, connor-mccarthy commented on github-orgs/kubeflow/org.yaml
> +        - jocstaa
I think this should be capitalized

2022-10-04 16:25 UTC, connor-mccarthy commented
/lgtm

2022-10-04 16:32 UTC, chensun reviewed
/approve

2022-10-04 16:35 UTC, merged