Requesting addition of "sen-sam" to Kubeflow org
kubeflow/internal-acls pull request #575
Opened 2022-10-05 20:37 UTC by sen-sam

2022-10-05 22:09 UTC, connor-mccarthy commented
/ok-to-test

2022-10-06 19:58 UTC, connor-mccarthy requested changes

2022-10-06 19:58 UTC, connor-mccarthy commented on github-orgs/kubeflow/org.yaml
> +        - sen-sam
This should be one name higher to be alphabetized

2022-11-03 15:56 UTC, sen-sam commented
/assign @connor-mccarthy

2022-11-03 16:01 UTC, connor-mccarthy commented
/lgtm

/assign @chensun for approval

2022-11-03 20:17 UTC, chensun approved these changes

2022-11-03 20:18 UTC, merged