Requesting membership for vrajjbhatt
kubeflow/internal-acls pull request #721
Opened 2024-11-09 16:52 UTC by vrajjbhatt

Requesting membership for vrajjbhatt for Kubeflow and Kserve Wg contribution

2024-11-09 20:17 UTC, terrytangyuan requested changes
Please add details for your contrition

2024-11-10 06:13 UTC, vrajjbhatt commented
> Please add details for your contrition

[](https://github.com/kubeflow/community/issues/775#issue-2592717205)
Here as mentioned being part of release team WG liaison for Pipelines and kserve WG, team is unable to assign me issues.

[](https://github.com/kubeflow/community/issues/775#issuecomment-2454995478)
[](https://github.com/kubeflow/community/issues/775#issuecomment-2455003033)

2024-12-02 19:04 UTC, varodrig commented
@terrytangyuan  to review/approve

2024-12-02 19:35 UTC, terrytangyuan approved these changes
Thanks!

/lgtm
/approve

2024-12-02 20:49 UTC, varodrig commented
@vrajjbhatt  please sign off your commits otherwise the PR cannot be merged. 
Check https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits to learn how to sign off your contributions.

as part of the [Contributing Guide](https://www.kubeflow.org/docs/about/contributing/ )

2025-07-17 00:29 UTC, closed without merging